package models

type Cake struct {
	Id   int
	Name string
	Cost string
	Img  string
}

var Cakes = []Cake{
	{
		Id:   1,
		Name: "Торт 1",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake1.jpg"},
	{Id: 2,
		Name: "Торт 2",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake2.jpg"},
	{Id: 3,
		Name: "Торт 3",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake3.jpg"},
	{Id: 4,
		Name: "Торт 4",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake4.jpg"},
	{Id: 5,
		Name: "Торт 5",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake5.jpg"},
	{Id: 6,
		Name: "Торт 6",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake6.jpg"},
	{Id: 7,
		Name: "Торт 7",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake7.jpg"},
	{Id: 8,
		Name: "Торт 8",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake8.jpg"},
	{Id: 9,
		Name: "Торт 9",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake9.jpg"},
	{Id: 10,
		Name: "Торт 10",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake10.jpg"},
	{Id: 11,
		Name: "Торт 11",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake11.jpg"},
	{Id: 12,
		Name: "Торт 12",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake12.jpg"},
	{Id: 13,
		Name: "Торт 13",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake13.jpg"},
	{Id: 14,
		Name: "Торт 14",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake14.jpg"},
	{Id: 15,
		Name: "Торт 15",
		Cost: "2500 ₽ за 1 кг",
		Img:  "/static/images/cakes/cake15.jpg"},
}
